engines:
  eslint:
    enabled: true

ratings:
  paths:
  - "lib/**.js"

exclude_patterns:
  - "riot+compiler.js"
  - "riot+compiler.min.js"
  - "riot.csp.js"
  - "riot.js"
  - "riot.min.js"
  - "test/**"