language: node_js

sudo: false
dist: trusty

addons:
  chrome: stable

node_js:
  - 8

branches:
  only:
    - master
    - dev
    - next

script:
  make riot

after_success:
  test $TRAVIS_PULL_REQUEST == "false" && make test-sauce && make test-coveralls

cache:
  directories:
    - node_modules

notifications:
    email: false
